# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170104_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
